[tools]
hk = "latest"
java = "21"
node = "lts"
"npm:ktfmt" = "latest"
prettier = "latest"
pkl = "latest"
actionlint = "latest"
shellcheck = "latest"
"npm:google-java-format" = "latest"
"npm:http-server" = "latest"

[settings]
lockfile = true
experimental = true

[hooks]
postinstall = "hk install"

[tasks]
check = "hk check --all"
fix = "hk fix --all"
demo-jvm = "./gradlew :demo-app:run"
demo-js = "./gradlew :demo-app:jsBrowserDevelopmentRun"
demo-wasm = "./gradlew :demo-app:wasmBrowserDevelopmentRun"
demo-macos = "./gradlew :demo-app:runDebugExecutableMacosArm64"
demo-android = [
  "./gradlew :demo-app:installDebug",
  "adb shell am start -n co.pokeapi.pokekotlin.demoapp/co.pokeapi.pokekotlin.demoapp.MainActivity",
]
demo-ios = "echo Not Implemented - Use XCode to run && exit 1"
