name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
          submodules: recursive
      - uses: "./.github/actions/setup"
      - run: "mise run test-server &"
      - run: "./gradlew allTests"

  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: "./gradlew generateDocs"
      - uses: "actions/upload-pages-artifact@v3"
        with:
          path: "build/docs"

  format:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: mise fix
      - run: |
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config user.name "github-actions[bot]"
          git diff --exit-code || (git add . && git commit -m 'Apply mise fix' && git push)
          git diff --exit-code

  check-hk:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: mise check

  all-good:
    needs:
      - "test"
      - "format"
      - "check-hk"
      - "build-docs"
    runs-on: "ubuntu-latest"
    steps:
      - run: "echo 'All checks passed!'"
