---
name: "Daily"

on:
  schedule:
    - cron: "00 10 * * *"
  workflow_dispatch:

jobs:
  check-last-run:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "octokit/request-action@v2.x"
        id: "check-last-run"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          route: |
            GET /repos/${{github.repository}}/actions/workflows/daily.yml/runs?per_page=1&status=completed"
    outputs:
      last_sha: |
        ${{fromJson(steps.check-last-run.outputs.data).workflow_runs[0].head_sha }}"

  publish-maven-snapshot:
    needs: ["check-last-run"]
    if: "${{ needs.check-last-run.outputs.last_sha != github.sha }}"
    runs-on: "ubuntu-latest"
    permissions:
      packages: "write"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: "./gradlew :publishAllPublicationsToGitHubPackagesRepository"
        env:
          ORG_GRADLE_PROJECT_GitHubPackagesPassword:
            "${{ secrets.GITHUB_TOKEN }}"
          ORG_GRADLE_PROJECT_GitHubPackagesUsername: "${{ github.actor }}"

  publish-npm-snapshot:
    needs: ["check-last-run"]
    if: "${{ needs.check-last-run.outputs.last_sha != github.sha }}"
    runs-on: "ubuntu-latest"
    permissions:
      packages: "write"
    steps:
      - uses: "actions/checkout@v4"
        with:
          fetch-depth: 0
      - uses: "./.github/actions/setup"
      - run: "./gradlew :publishJsPackageToGithubRegistry"
        env:
          ORG_GRADLE_PROJECT_GitHubPackagesPassword:
            "${{ secrets.GITHUB_TOKEN }}"
